version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./localhost:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APP_ENV=dev
      # 添加下面两行防止 Composer 内存错误 ↓
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_ALLOW_SUPERUSER=1
    # 添加健康检查 ↓
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
